[project]
name = "yt-to-audio-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mutagen>=1.47.0",
    "pedalboard>=0.9.21",
    "pytubefix>=10.3.6",
    "requests>=2.32.5",
]
